[build-system]
requires = ["hatchling>=1.24"]
build-backend = "hatchling.build"

[project]
name = "kube-models"
version = "0.0.3"
requires-python = ">=3.10"
description = "Python dataclasses for all Kubernetes built-in resources (v1.23+)"
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "Nik Paushkin", email = "nik@puzl.cloud" }]

[dependency-groups]
test = ["coverage"]

[tool.hatch.build.targets.wheel]
packages = ["src/kube_models"]
