[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/kubesdk_cli"]

[project]
name = "kubesdk-cli"
version = "0.0.0"
description = "Kubernetes API models and CRD generator"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [{ name = "nik@puzl.cloud" }]

dependencies = [
    "datamodel-code-generator[http]==0.33.0",
    "pydantic>=2.4,<3",
    "jinja2>=3.1",
    "requests==2.32.5"
]
