[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kubesdk"
version = "0.0.2"
description = "Fast, fully typed Kubernetes client for Python."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [{ name = "Nik Paushkin", email = "nik@puzl.cloud" }]

dependencies = [
    "aiohttp==3.12.15",
    "PyYAML==6.0.3",
    "kube-models==0.*"
]

[dependency-groups]
test = ["jsonpatch", "coverage"]

[tool.hatch.build.targets.wheel]
packages = ["src/kubesdk"]

[project.optional-dependencies]
cli = ["kubesdk-cli"]
